### ISSUE TITLE
We could be *way* more intelligent about how we send messages.

### ISSUE THREAD

**Issue by Chalos-Atiesh** [Chalos-Atiesh/GuildTradeskills#26]
Currently:
1. We send a timestamp whisper to every online guild member individually.
2. All of those guild members respond with a GET or POST whisper of their own including records the original sender doesn't have. For each timestamp. Do nothing if there's nothing to be done.
3. The original sender either receives the POST or sends a POST if the guild member send a GET.

This produces a *ton* of excess messaging.

I'm thinking something like:
1. The user sends a timestamp to the *guild*.
2. The guild sends their timestamps to the guild and assembles a list of who has the latest.
3. If the owner of the timestamp is online they just send a post to the guild.
4. If the owner is not online everyone compiles a list of who has the latest and performs a random vote on who should send the post.
5. The winner sends the post.

**Comment by Chalos-Atiesh** [comment]
https://github.com/Chalos-Atiesh/GuildTradeskills/commit/d05a222ec06f117e52dc9465fcd9f9e588857778

**Comment by StephanDufour** [comment]
In network engineering there is a routing protocol named OSPF which works in a similar way:
https://cisco.goffinet.org/ccna/ospf/election-dr-bdr-ospf/

At start, the network elects a Designated Router (DR) and Backup DR (BDR) for redundancy.
This done by a priority in each router, in case of equality some other uniq ID is used.

First a BDR is elected then if there is no DR, the BDR becomes DR and a new BDR is elected.
DR stays the same even if a new router with higher priority appears.

All others are DRO, they communicate only with DR (maybe also BDR).

Not related to OPSF but coding:
Some trick commonly used is to compute a hash of all objects in database.
If the hash is the same between peers then no updated is needed.
If the hash is not the same you can send the hash of a group of object or the list of hashes of all objects to identify which one is missing or has changed and only update this part.

**Comment by Chalos-Atiesh** [comment]
I didn't implement a BDR since there doesn't necessarily need to be a leader. I also didn't want to place sole responsibility on one elected leader as that would place strain on their system so went with a randomized distributed post. The only caveat being that, if the character who owns the tradeskill is online, everyone votes for that person so they are the auto-winner.
There's also the added benefit that, in general, people in the character's guild are trusted so we don't need to worry too much about validation or security.
Where it gets massively more complicated is in the request feature I added. The logic there is... complicated.
