### ISSUE TITLE
Some users are experiencing "The number of messages that can be sent is limited..." errors when broadcasting is enabled.

### ISSUE THREAD

**Issue by Chalos-Atiesh** [Chalos-Atiesh/GuildTradeskills#52]
Not experienced in testing.
Possibly due to a conflict with another addon or an issue with large pushes.

**Comment by Chalos-Atiesh** [comment]
https://github.com/Chalos-Atiesh/GuildTradeskills/commit/12609c5e5686fc86f6c75be14d9dd29472450961

**Comment by StephanDufour** [comment]
It could be linked to broadcast + forward mecanism.
If you have 4 people A, B, C, D with addon.

A broadcasts to B,C and D
B forwards to C and D. C to B and D. D to B and C
Depending on how code is written, they may reforward endlessly among themselves and multiplying the number of messages achieving rate limit.

One common way to avoid this is adding a TTL (time to live) to the message. Decreasing it's value at each forward and stopping at TTL=0.
You can also append the character name to a list along the forward path and limit it to n people.
