### ISSUE TITLE
GuildTradeskills\Modules\DB\DBCharacter.lua:164: attempt to index global 'character' (a nil value)

### ISSUE THREAD

**Issue by luitzifa** [Chalos-Atiesh/GuildTradeskills#55]
While testing german localization i noticed that i'm unable to execute the commands:
```
/gt removeprofession alchemy
/gt broadcast receive
```
Add first i thought it's maybe a problem with the localozation, but back to english client, i got the same problem.

What i mean with unable:
I type the command and when i press "Enter" just nothing happens, the inputfield remains open and editable.

**Comment by Chalos-Atiesh** [comment]
Good catch. Here's the stack trace for that error.
Message: ...e\AddOns\GuildTradeskills\Modules\DB\DBCharacter.lua:164: attempt to index global 'character' (a nil value)
Time: Sun Jul  5 03:58:24 2020
Count: 1
Stack: ...e\AddOns\GuildTradeskills\Modules\DB\DBCharacter.lua:164: attempt to index global 'character' (a nil value)
[C]: ?
...e\AddOns\GuildTradeskills\Modules\DB\DBCharacter.lua:164: in function `DeleteProfession'
...rface\AddOns\GuildTradeskills\Modules\Profession.lua:257: in function `DeleteProfession'
...nterface\AddOns\GuildTradeskills\Modules\Command.lua:115: in function `?'
...nterface\AddOns\GuildTradeskills\Modules\Command.lua:66: in function `DoCommand'
...nterface\AddOns\GuildTradeskills\Modules\Command.lua:50: in function `?'
...dOnSkins\Libs\Ace3\AceConsole-3.0\AceConsole-3.0.lua:94: in function `?'
Interface\FrameXML\ChatFrame.lua:4690: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4351: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4387: in function <Interface\FrameXML\ChatFrame.lua:4383>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
