### ISSUE TITLE
Language is mixed

### ISSUE THREAD

**Issue by luitzifa** [Chalos-Atiesh/GuildTradeskills#62]
When adding profession with english client, they are not translated to german, when i switch the client language. Search is also affected by this.

I have no one to test yet, by i guess it's also the case when a receive date from another player, isn't it?

![mixed_language](https://user-images.githubusercontent.com/8862016/87086543-0e29df80-c232-11ea-95e2-cc38c5d5d63d.jpg)

**Comment by Chalos-Atiesh** [comment]
Unfortunately this is a limitation of the Blizzard API. We are not given IDs for tradeskills so must rely on the name of the skill to act as an ID.

**Comment by luitzifa** [comment]
too bad :(
