### ISSUE TITLE
Sync not working between different wow client  languages 

### ISSUE THREAD

**Issue by ixidion** [Chalos-Atiesh/GuildTradeskills#80]
Players with different client versions are not able to sync their tradeskills, when using different client versions, e.g. a player with a german client can not sync with an english client version and vice versa.

May the reason is: The sync should be based on IDs and not based on localized strings.

**Comment by Chalos-Atiesh** [comment]
That is correct. Unfortunately Blizzard, in the infinite wisdom, does not make those IDs available to addons.
I do have a potential fix for this in mind but it requires an extensive rework of most aspects and I don't have the time currently to do that.
